baseURL = "https://log.jubril.me"
languageCode = "en-us"
title = "$> cat /var/log/e770r"
theme = "hugo-notepadium"
copyright = "©2021 s1ntaxe770r"
googleAnalytics="G-D6NJ1ZKSX9"
[params.nav]
showCategories = true       
showTags = true  

[params]
logo = "https://avatars.githubusercontent.com/u/53065463?v=4"
slogan = "logging my experiences one blog at a time ~"
readingTime = false  


[params.profile]
enable = true
avatar = "https://avatars.githubusercontent.com/u/53065463?v=4"
name = "s1ntaxe770r"
twitter = "s1ntaxe770r" 
github = "s1ntaxe770r"
docker = "e770r"  

[params.share]
enable = true
inlineToolId = ""


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
    
[taxonomies]
category = "categories"
tag = "tags"

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

